#
# BASE CONFIGURATION
#

# `base_url` should only be changed if your site isn't hosted at the root of a domain.
# `domain` is used to generate absolute URLs. (required to generate a valid feed)
#
#   Example:
#       http://my-site.com/
#           base_url: /
#           domain: my-site.com
#       http://my-site.com/my-blog/
#           base_url: /my-blog/
#           domain: my-site.com
base_url: /
domain: mynt.uhnomoli.com


#
# METADATA
#

# Used in header meta tags and the site feed. (required to generate a valid feed)
author: Andrew Fricke
# A description of your site to be used in header meta tags.
description:
# Used in the site feed.
email: andrew@uhnomoli.com
# Your site's subtitle.
subtitle: static done simple
# Your site's title. (required to generate a valid feed)
title: mynt


#
# CONTENT SETTINGS
#
archive_layout: archive.html
archives_url: /news/archives/
posts_url: /news/<year>/<month>/<day>/<slug>/
tag_layout: tag.html
tags_url: /news/archives/


#
# SITE DATA
#
powering:
    - name: mynt.uhnomoli.com
      url: http://mynt.uhnomoli.com/
      source: https://github.com/Anomareh/mynt/tree/master/docs
    - name: uhnomoli.com
      url: http://uhnomoli.com/
      source: https://github.com/Anomareh/uh.nom.o.li
    - name: samesake.com
      url: http://samesake.com/
    - name: hynek.me
      url: http://hynek.me/
      source: https://github.com/hynek/homepage
    - name: shamansir.github.com/blog/
      url: http://shamansir.github.io/blog/
      source: https://github.com/shamansir/blog
    - name: roguelynn.com
      url: http://www.roguelynn.com/
      source: https://github.com/econchick/roguelynn
    - name: tummy.com
      url: http://www.tummy.com/
    - name: pyladies.com
      url: http://www.pyladies.com/
      source: https://github.com/pyladies/pyladies
    - name: newcoder.io
      url: http://newcoder.io/
      source: https://github.com/econchick/new-coder
    - name: bana.netspin.hu
      url: http://bana.netspin.hu/
    - name: python.org.tw
      url: http://www.python.org.tw/
      source: https://github.com/lucemia/taiwan.py
    - name: blog.pedesen.de
      url: http://blog.pedesen.de/

